### ISSUE TITLE
Incorrect batches showing when changing batch confirmation

### ISSUE THREAD

**Issue by mcmcgrath13** [jaryncolbert/recurse-world-map#63]
I originally confirmed for one batch then changed to a later one, but both batches show in the app

<img width="831" alt="image" src="https://user-images.githubusercontent.com/24885580/191094021-7746220c-d359-42aa-9f3b-400a4ef46bbf.png">

**Comment by jaryncolbert** [comment]
@mcmcgrath13 -- you're in there correctly now!
<img width="306" alt="Screen Shot 2023-04-05 at 11 38 28 PM" src="https://user-images.githubusercontent.com/1173252/230266350-cbf2e059-f155-442a-ac15-71ea14f24714.png">

I ended up setting up the DB again recently, and your batch data was reprocessed. The update script only inserts new records, but doesn't check for updates. So once your original batch info was inserted, it wasn't updated (until I set up a fresh DB when upgrading Heroku).
